general:
  buildTool: "custom"

stages:
  Build:
    enabled: false

  Acceptance:
    enabled: false

  Release:
    enabled: true

steps:
  cloudFoundryDeploy:
    apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    org: "ccb1d7c7trial"
    space: "dev"
    credentialsId: "btpauthsecops"