general:
  buildTool: "npm"
  productiveBranch: "test"

stages:
  Build:
    enabled: true
  Acceptance:
    enabled: false
  Release:
    enabled: true

steps:
  npmExecuteScripts:
    runScripts:
      - install
      - build

  cloudFoundryDeploy:
    apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    org: "ccb1d7c7trial"
    space: "dev"
    credentialsId: "btpauthsecops"