---
stages:
  build:
    buildTool: "npm"
    buildToolVersion: "Node_22"
    buildDescriptor: "package.json"
    npmScript: "build"

  acceptance:
    cloudFoundryDeploy:
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "ccb1d7c7trial"
      space: "dev"
      credential: "btpauthsecops"

  release:
    cloudFoundryDeploy:
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "ccb1d7c7trial"
      space: "dev"
      credential: "btpauthsecops"