---
stages:
  build:
    buildTool: "npm"
    buildToolVersion: "N22"
    buildDescriptor: "package.json"
    npmScript: "build"


  release:
    cfDeploy:
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "ccb1d7c7trial"
      space: "dev"
      credential: "btpauthsecops"