---
general:
  buildTool: "npm"

stages:
  Build:
    buildToolVersion: "N22"
    npmExecuteBuild: true
    npmBuildScript: "build"

  Deploy:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "ccb1d7c7trial"
    cfSpace: "dev"
    cfCredentialsId: "btpauthsecops"
    cfAppName: "user-app"